//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donacion
    {
        public int id { get; set; }
        public string nombre_mpio { get; set; }
        public string nombre_arbol { get; set; }
        public Nullable<int> cantidad { get; set; }
    }
}
